export default function Home() {
  return (
    <main>
      <nav className="nav shell"><a className="wordmark" href="#top">AF<span>.</span></a><div className="nav-links"><a href="#work">Selected work</a><a href="#about">About</a><a href="#contact" className="nav-contact">Let&apos;s talk <span>↗</span></a></div></nav>
      <section className="hero shell" id="top"><div className="hero-topline"><span>Available for select projects</span><span>Based in Lahore / Pakistan</span></div><div className="hero-content"><p className="eyebrow">Independent designer &amp; developer</p><h1>Akbar<br /><em>Farooq</em></h1><p className="hero-intro">I shape thoughtful digital experiences where sharp design meets useful technology.</p><a className="circle-link" href="#work" aria-label="Scroll to selected work">↓</a></div><div className="hero-footer"><span>01 - 04</span><span>Scroll to explore</span></div></section>
      <section className="statement shell" id="about"><p className="section-label">A little about me</p><div><h2>Making the complex<br /><span>feel simple.</span></h2><p className="statement-copy">I&apos;m a multidisciplinary creative who enjoys turning big ideas into clear, memorable products. From first sketch to final pixel, I care about the details that make digital things feel human.</p><a className="text-link" href="mailto:hello@akbarfarooq.dev">More about me <span>↗</span></a></div></section>
      <section className="work shell" id="work"><div className="section-heading"><p className="section-label">Selected work</p><span>(2022 - 2025)</span></div><div className="projects"><a className="project project-lime" href="#contact"><div className="project-art art-orbit"><span>n/</span></div><div className="project-meta"><h3>Noma Studios</h3><span>Brand identity / Digital</span><strong>↗</strong></div></a><a className="project project-blue" href="#contact"><div className="project-art art-grid"><span>FORM<br />FOLLOWS<br />FEELING</span></div><div className="project-meta"><h3>Field Notes</h3><span>Editorial / Art direction</span><strong>↗</strong></div></a><a className="project project-orange" href="#contact"><div className="project-art art-type"><span>common<br /><i>ground</i></span></div><div className="project-meta"><h3>Common Ground</h3><span>Product design / Strategy</span><strong>↗</strong></div></a></div></section>
      <footer className="footer shell" id="contact"><p className="section-label">Have a good one?</p><h2>Let&apos;s make<br /><em>something good.</em></h2><a className="email-link" href="mailto:hello@akbarfarooq.dev">hello@akbarfarooq.dev <span>↗</span></a><div className="footer-bottom"><span>(c) 2025 Akbar Farooq</span><div><a href="#top">Back to top ^</a><a href="https://www.linkedin.com" target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div></footer>
    </main>
  );
}
